version: '2'
services:
    database:
        image: mysql:5.6
        restart: always
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
        environment:
            MYSQL_ROOT_PASSWORD: foradian
            MYSQL_DATABASE: fedena_ultimate
        volumes:
            - "./mysql/data:/var/lib/mysql"
            - "./mysql/backup:/backup"
        ports:
            - "3307:3306"
        networks:
          vpcbr:
            ipv4_address: 11.11.0.2
    web:
        build: .
        # volumes:
        #     - "./html/:/var/www/html"
        ports:
            - "3001:3000"
        restart: always
        tty: true
        #command: bash -c '/sbin/httpd -k start'
        networks:
          vpcbr:
            ipv4_address: 11.11.0.3
networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 11.11.0.0/16
         gateway: 11.11.0.1
