version: '3'
services:
    web:
        build: .
        # image: asanchez75/php-sqlsrv:d8
        # volumes:
        #     - "./html/:/var/www/html"
        # ports:
        #     - "80:80"
        # restart: always
        # #command: bash -c '/sbin/httpd -k start'
        # depends_on:
        #     - mysql
    # mysql:
    #     image: mysql:5.6
    #     restart: always
    #     environment:
    #         MYSQL_ROOT_PASSWORD: 123456
    #     volumes:
    #         - "./mysql/mysql-data:/var/lib/mysql"
    #         - "./mysql/backup:/backup"
    #     ports:
    #         - "3309:3306"
